version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - APP_CORS_ORIGINS=${APP_CORS_ORIGINS}
    container_name: slingercode-drive-server
    ports:
      - 8000:8000

  client:
    depends_on:
      - server
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    container_name: slingercode-drive-client
    ports:
      - 80:80
